# Generated by Django 3.2 on 2021-04-08 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('auth', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 8, 9, 42, 3, 43630))),
            ],
        ),
    ]
