# Generated by Django 3.2 on 2021-04-09 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0002_auto_20210409_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='upload_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 9, 19, 8, 1, 542278)),
        ),
    ]
