# Generated by Django 3.2 on 2021-04-09 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0003_auto_20210409_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='image',
            field=models.ImageField(default='', upload_to='upload_img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 9, 19, 9, 13, 240274)),
        ),
    ]
