# Generated by Django 3.2 on 2021-04-11 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0004_auto_20210409_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 11, 10, 28, 52, 333461)),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='upload_img/'),
        ),
    ]
