# Generated by Django 3.2 on 2021-04-11 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0005_auto_20210411_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 11, 10, 29, 0, 971288)),
        ),
    ]
