# Generated by Django 3.2 on 2021-04-11 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0006_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 11, 10, 35, 29, 716096)),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload_img/'),
        ),
    ]
