# Generated by Django 3.2 on 2021-04-11 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0007_auto_20210411_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 11, 12, 36, 10, 368343)),
        ),
        migrations.AlterField(
            model_name='temp',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload_img/'),
        ),
    ]
