# Generated by Django 3.2 on 2021-04-11 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0008_auto_20210411_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='image',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 11, 12, 54, 22, 394186)),
        ),
    ]
