# Generated by Django 3.2 on 2021-04-12 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_1', '0009_auto_20210411_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='upload_file/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 12, 8, 19, 53, 417650)),
        ),
    ]
